apiVersion: v1
kind: ConfigMap
metadata:
  name: "log-config"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ourapp.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logFilter.logLevel | quote }}
