apiVersion: v1
kind: Service
metadata:
  name: {{ include "ourapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ourapp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "ourapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: ourapp
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: logfilter
      port: 5000
      targetPort: logfilter
      protocol: TCP
